// Metadata extraction utilities for rich detail display
//
// Provides DetailLevel enum and helper functions to extract
// visibility, generics, deprecation, attributes, and function modifiers
// from rustdoc-types structures.

use rustdoc_types::{
    Abi, Attribute, Deprecation, FunctionHeader, GenericBound, GenericParamDef,
    GenericParamDefKind, Generics, Visibility, WherePredicate,
};

/// Level of detail for metadata display
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum DetailLevel {
    /// Minimal mode: signatures only, no metadata
    Minimal,
    /// Standard mode: signatures + visibility + generics (default)
    Standard,
    /// Detailed mode: full metadata including attributes, deprecation, function modifiers
    Detailed,
}

impl DetailLevel {
    /// Determine detail level from CLI flags
    /// - --minimal forces Minimal
    /// - --detailed forces Detailed
    /// - otherwise Standard
    pub fn from_flags(minimal: bool, detailed: bool) -> Self {
        if minimal {
            Self::Minimal
        } else if detailed {
            Self::Detailed
        } else {
            Self::Standard
        }
    }

    /// Check if this level should include visibility
    pub fn includes_visibility(self) -> bool {
        matches!(self, Self::Standard | Self::Detailed)
    }

    /// Check if this level should include generics
    pub fn includes_generics(self) -> bool {
        matches!(self, Self::Standard | Self::Detailed)
    }

    /// Check if this level should include attributes
    pub fn includes_attributes(self) -> bool {
        matches!(self, Self::Detailed)
    }

    /// Check if this level should include deprecation
    pub fn includes_deprecation(self) -> bool {
        matches!(self, Self::Detailed)
    }

    /// Check if this level should include function modifiers
    pub fn includes_function_modifiers(self) -> bool {
        matches!(self, Self::Detailed)
    }
}

impl Default for DetailLevel {
    fn default() -> Self {
        Self::Standard
    }
}

/// Convert visibility to display string
///
/// Handles all rustdoc visibility variants:
/// - Public -> "pub"
/// - Default -> "" (private)
/// - Crate -> "pub(crate)"
/// - Restricted { path, .. } -> "pub(in path)"
pub fn visibility_to_string(vis: &Visibility) -> String {
    match vis {
        Visibility::Public => "pub".to_string(),
        Visibility::Default => String::new(),
        Visibility::Crate => "pub(crate)".to_string(),
        Visibility::Restricted { path, .. } => {
            format!("pub(in {})", path)
        }
    }
}

/// Format generics as Rust syntax string
///
/// Filters synthetic parameters and formats generics in standard Rust syntax.
/// Returns None if there are no non-synthetic parameters and no where clauses.
pub fn format_generics(generics: &Generics) -> Option<String> {
    // Filter out synthetic parameters (impl Trait generated by compiler)
    let params: Vec<&GenericParamDef> = generics
        .params
        .iter()
        .filter(|p| !is_synthetic_param(p))
        .collect();

    // If no params and no where clauses, return None
    if params.is_empty() && generics.where_predicates.is_empty() {
        return None;
    }

    let mut result = String::new();

    // Format type/lifetime/const parameters
    if !params.is_empty() {
        let param_strings: Vec<String> = params.iter().map(|p| format_generic_param(p)).collect();
        result.push('<');
        result.push_str(&param_strings.join(", "));
        result.push('>');
    }

    // Format where clauses
    if !generics.where_predicates.is_empty() {
        let where_clauses: Vec<String> = generics
            .where_predicates
            .iter()
            .map(|wp| format_where_predicate(wp))
            .collect();
        result.push_str(" where ");
        result.push_str(&where_clauses.join(", "));
    }

    Some(result)
}

/// Check if a generic parameter is synthetic (impl Trait generated)
fn is_synthetic_param(param: &GenericParamDef) -> bool {
    matches!(
        &param.kind,
        GenericParamDefKind::Type {
            is_synthetic: true,
            ..
        }
    )
}

/// Format a single generic parameter
fn format_generic_param(param: &GenericParamDef) -> String {
    match &param.kind {
        GenericParamDefKind::Type {
            bounds,
            default,
            is_synthetic: false,
        } => {
            let mut result = param.name.clone();

            // Add bounds: T: Clone + Debug
            if !bounds.is_empty() {
                let bound_strings: Vec<String> =
                    bounds.iter().map(|b| format_generic_bound(b)).collect();
                result.push_str(": ");
                result.push_str(&bound_strings.join(" + "));
            }

            // Add default: T = String (simplified)
            if default.is_some() {
                result.push_str(" = ..."); // Simplified - don't format complex types
            }

            result
        }
        GenericParamDefKind::Lifetime { outlives } => {
            let mut result = param.name.clone();
            if !outlives.is_empty() {
                result.push_str(": ");
                result.push_str(&outlives.join(" + "));
            }
            result
        }
        GenericParamDefKind::Const { type_, default } => {
            let type_str = format_type_simple(type_);
            let mut result = format!("const {}: {}", param.name, type_str);
            if let Some(default_value) = default {
                result.push_str(" = ");
                result.push_str(default_value);
            }
            result
        }
        // Should never reach here due to synthetic filtering
        _ => param.name.clone(),
    }
}

/// Format a generic bound
fn format_generic_bound(bound: &GenericBound) -> String {
    match bound {
        GenericBound::TraitBound {
            trait_,
            generic_params,
            ..
        } => {
            // trait_ is a Path, not a Type
            let trait_path = trait_.path.clone();
            if generic_params.is_empty() {
                trait_path
            } else {
                // Handle HRTBs: for<'a> Trait<'a>
                let params: Vec<String> = generic_params
                    .iter()
                    .map(|p| format_generic_param(p))
                    .collect();
                format!("for<{}> {}", params.join(", "), trait_path)
            }
        }
        GenericBound::Outlives(lifetime) => {
            // Remove surrounding quotes if present
            lifetime.trim_matches('"').to_string()
        }
        GenericBound::Use(_) => {
            // Precise capturing - format as "use<...>" (simplified)
            "use<...>".to_string()
        }
    }
}

/// Format a where predicate
fn format_where_predicate(wp: &WherePredicate) -> String {
    match wp {
        WherePredicate::BoundPredicate {
            type_,
            bounds,
            generic_params,
        } => {
            let type_str = format_type_simple(type_);
            let bound_strs: Vec<String> = bounds.iter().map(|b| format_generic_bound(b)).collect();
            let bounds_str = bound_strs.join(" + ");

            if generic_params.is_empty() {
                format!("{}: {}", type_str, bounds_str)
            } else {
                let params: Vec<String> = generic_params
                    .iter()
                    .map(|p| format_generic_param(p))
                    .collect();
                format!("for<{}> {}: {}", params.join(", "), type_str, bounds_str)
            }
        }
        WherePredicate::LifetimePredicate { lifetime, outlives } => {
            if outlives.is_empty() {
                lifetime.to_string()
            } else {
                format!("{}: {}", lifetime, outlives.join(" + "))
            }
        }
        WherePredicate::EqPredicate { lhs, rhs: _ } => {
            // Simplified - just show lhs exists with some constraint
            format!("{} = ...", format_type_simple(lhs))
        }
    }
}

/// Format a type for display (simplified version)
fn format_type_simple(type_: &rustdoc_types::Type) -> String {
    match type_ {
        rustdoc_types::Type::ResolvedPath(path) => {
            let mut result = path.path.clone();
            if let Some(args) = &path.args {
                result.push_str(&format_generic_args_simple(args));
            }
            result
        }
        rustdoc_types::Type::Generic(name) => name.clone(),
        rustdoc_types::Type::Primitive(name) => name.clone(),
        rustdoc_types::Type::FunctionPointer(fp) => {
            let inputs: Vec<String> = fp
                .sig
                .inputs
                .iter()
                .map(|(_, ty)| format_type_simple(ty))
                .collect();
            let output_str = match &fp.sig.output {
                Some(out) => format_type_simple(out),
                None => "()".to_string(),
            };
            if fp.sig.inputs.is_empty() {
                format!("fn() -> {}", output_str)
            } else {
                format!("fn({}) -> {}", inputs.join(", "), output_str)
            }
        }
        rustdoc_types::Type::Tuple(types) => {
            if types.is_empty() {
                "()".to_string()
            } else {
                format!(
                    "({})",
                    types
                        .iter()
                        .map(|t| format_type_simple(t))
                        .collect::<Vec<_>>()
                        .join(", ")
                )
            }
        }
        rustdoc_types::Type::Slice(inner) => format!("[{}]", format_type_simple(inner)),
        rustdoc_types::Type::Array { type_, len } => {
            format!("[{}; {}]", format_type_simple(type_), len)
        }
        rustdoc_types::Type::Pat { type_, .. } => format_type_simple(type_),
        rustdoc_types::Type::ImplTrait(bounds) => {
            let bound_strs: Vec<String> = bounds.iter().map(|b| format_generic_bound(b)).collect();
            format!("impl {}", bound_strs.join(" + "))
        }
        rustdoc_types::Type::DynTrait(dt) => {
            let trait_strs: Vec<String> = dt
                .traits
                .iter()
                .map(|poly_trait| {
                    let mut s = poly_trait.trait_.path.clone();
                    if !poly_trait.generic_params.is_empty() {
                        let params: Vec<String> = poly_trait
                            .generic_params
                            .iter()
                            .map(|p| format_generic_param(p))
                            .collect();
                        s = format!("for<{}> {}", params.join(", "), s);
                    }
                    s
                })
                .collect();
            let mut result = format!("dyn {}", trait_strs.join(" + "));
            if let Some(lt) = &dt.lifetime {
                result.push_str(" + ");
                result.push_str(lt);
            }
            result
        }
        rustdoc_types::Type::BorrowedRef {
            lifetime,
            type_,
            is_mutable,
        } => {
            let mut result = String::new();
            result.push('&');
            if let Some(lt) = lifetime {
                result.push_str(lt);
                result.push(' ');
            }
            if *is_mutable {
                result.push_str("mut ");
            }
            result.push_str(&format_type_simple(type_));
            result
        }
        rustdoc_types::Type::QualifiedPath {
            name,
            args: _,
            self_type,
            trait_,
        } => {
            let self_str = format_type_simple(self_type);
            if let Some(trait_type) = trait_ {
                format!("<{} as {}>::{}", self_str, trait_type.path, name)
            } else {
                format!("{}::{}", self_str, name)
            }
        }
        rustdoc_types::Type::RawPointer { is_mutable, type_ } => {
            let ptr = if *is_mutable { "*mut " } else { "*const " };
            format!("{}{}", ptr, format_type_simple(type_))
        }
        rustdoc_types::Type::Infer => "_".to_string(),
    }
}

/// Format generic arguments (simplified)
fn format_generic_args_simple(args: &std::boxed::Box<rustdoc_types::GenericArgs>) -> String {
    match args.as_ref() {
        rustdoc_types::GenericArgs::AngleBracketed { args, .. } => {
            if args.is_empty() {
                return String::new();
            }
            let parts: Vec<String> = args
                .iter()
                .map(|arg| match arg {
                    rustdoc_types::GenericArg::Type(t) => format_type_simple(t),
                    rustdoc_types::GenericArg::Lifetime(l) => l.clone(),
                    rustdoc_types::GenericArg::Const(c) => c.expr.clone(),
                    rustdoc_types::GenericArg::Infer => "_".to_string(),
                })
                .collect();
            format!("<{}>", parts.join(", "))
        }
        rustdoc_types::GenericArgs::Parenthesized { inputs, output } => {
            let input_strs: Vec<String> = inputs.iter().map(|t| format_type_simple(t)).collect();
            match output {
                None => format!("({})", input_strs.join(", ")),
                Some(out) => format!("({}) -> {}", input_strs.join(", "), format_type_simple(out)),
            }
        }
        rustdoc_types::GenericArgs::ReturnTypeNotation => {
            // T::method(..) notation - return empty for now
            String::new()
        }
    }
}

/// Extract deprecation information
///
/// Returns Some((is_deprecated, deprecation_note)) if deprecated.
/// Note: "since" field is intentionally skipped per requirements.
pub fn extract_deprecation_info(
    deprecation: Option<&Deprecation>,
) -> Option<(bool, Option<String>)> {
    deprecation.map(|d| (true, d.note.clone()))
}

/// Extract semantic attributes
///
/// Filters attributes to return only semantically meaningful ones:
/// - #[must_use] or #[must_use("reason")]
/// - #[non_exhaustive]
///
/// Skips: Repr, AutomaticallyDerived, doc attrs, etc.
pub fn extract_semantic_attrs(attrs: &[Attribute]) -> Vec<String> {
    attrs
        .iter()
        .filter_map(|attr| match attr {
            Attribute::MustUse { reason } => {
                if let Some(r) = reason {
                    Some(format!("#[must_use(\"{}\")]", r))
                } else {
                    Some("#[must_use]".to_string())
                }
            }
            Attribute::NonExhaustive => Some("#[non_exhaustive]".to_string()),
            // Note: #[deprecated] is in Item.deprecation, not attrs
            _ => None,
        })
        .collect()
}

/// Extract function modifiers
///
/// Returns (is_const, is_async, is_unsafe, abi_string)
/// - abi_string is None for Rust ABI (the default)
/// - Non-Rust ABIs return Some("C"), Some("stdcall"), etc.
pub fn extract_function_modifiers(header: &FunctionHeader) -> (bool, bool, bool, Option<String>) {
    let abi_string = match &header.abi {
        Abi::Rust => None,
        Abi::C { .. } => Some("C".to_string()),
        Abi::Cdecl { .. } => Some("cdecl".to_string()),
        Abi::Stdcall { .. } => Some("stdcall".to_string()),
        Abi::Fastcall { .. } => Some("fastcall".to_string()),
        Abi::Aapcs { .. } => Some("aapcs".to_string()),
        Abi::Win64 { .. } => Some("win64".to_string()),
        Abi::SysV64 { .. } => Some("sysv64".to_string()),
        Abi::System { .. } => Some("system".to_string()),
        Abi::Other(name) => Some(name.clone()),
    };

    (
        header.is_const,
        header.is_async,
        header.is_unsafe,
        abi_string,
    )
}

/// Build function modifier prefix string
///
/// Returns prefix like "const async unsafe extern \"C\" " or empty string
pub fn format_function_modifiers(
    is_const: bool,
    is_async: bool,
    is_unsafe: bool,
    abi: Option<&str>,
) -> String {
    let mut parts = Vec::new();

    if is_const {
        parts.push("const".to_string());
    }
    if is_async {
        parts.push("async".to_string());
    }
    if is_unsafe {
        parts.push("unsafe".to_string());
    }
    if let Some(abi_str) = abi {
        if abi_str != "Rust" {
            parts.push(format!("extern \"{}\"", abi_str));
        }
    }

    if parts.is_empty() {
        String::new()
    } else {
        format!("{} ", parts.join(" "))
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    // =========================================================================
    // DetailLevel Tests
    // =========================================================================

    #[test]
    fn test_detail_level_from_flags() {
        assert_eq!(DetailLevel::from_flags(true, false), DetailLevel::Minimal);
        assert_eq!(DetailLevel::from_flags(false, true), DetailLevel::Detailed);
        assert_eq!(DetailLevel::from_flags(false, false), DetailLevel::Standard);
        assert_eq!(DetailLevel::from_flags(true, true), DetailLevel::Minimal); // minimal takes precedence
    }

    #[test]
    fn test_detail_level_default() {
        assert_eq!(DetailLevel::default(), DetailLevel::Standard);
    }

    #[test]
    fn test_detail_level_includes_visibility() {
        assert!(!DetailLevel::Minimal.includes_visibility());
        assert!(DetailLevel::Standard.includes_visibility());
        assert!(DetailLevel::Detailed.includes_visibility());
    }

    #[test]
    fn test_detail_level_includes_generics() {
        assert!(!DetailLevel::Minimal.includes_generics());
        assert!(DetailLevel::Standard.includes_generics());
        assert!(DetailLevel::Detailed.includes_generics());
    }

    #[test]
    fn test_detail_level_includes_attributes() {
        assert!(!DetailLevel::Minimal.includes_attributes());
        assert!(!DetailLevel::Standard.includes_attributes());
        assert!(DetailLevel::Detailed.includes_attributes());
    }

    #[test]
    fn test_detail_level_includes_deprecation() {
        assert!(!DetailLevel::Minimal.includes_deprecation());
        assert!(!DetailLevel::Standard.includes_deprecation());
        assert!(DetailLevel::Detailed.includes_deprecation());
    }

    #[test]
    fn test_detail_level_includes_function_modifiers() {
        assert!(!DetailLevel::Minimal.includes_function_modifiers());
        assert!(!DetailLevel::Standard.includes_function_modifiers());
        assert!(DetailLevel::Detailed.includes_function_modifiers());
    }

    // =========================================================================
    // Visibility Tests
    // =========================================================================

    #[test]
    fn test_visibility_to_string_public() {
        assert_eq!(visibility_to_string(&Visibility::Public), "pub");
    }

    #[test]
    fn test_visibility_to_string_default() {
        assert_eq!(visibility_to_string(&Visibility::Default), "");
    }

    #[test]
    fn test_visibility_to_string_crate() {
        assert_eq!(visibility_to_string(&Visibility::Crate), "pub(crate)");
    }

    #[test]
    fn test_visibility_to_string_restricted() {
        let vis = Visibility::Restricted {
            parent: rustdoc_types::Id(1),
            path: "::iter".to_string(),
        };
        assert_eq!(visibility_to_string(&vis), "pub(in ::iter)");

        let vis2 = Visibility::Restricted {
            parent: rustdoc_types::Id(2),
            path: "crate::internal".to_string(),
        };
        assert_eq!(visibility_to_string(&vis2), "pub(in crate::internal)");
    }

    // =========================================================================
    // Deprecation Tests
    // =========================================================================

    #[test]
    fn test_extract_deprecation_info_none() {
        assert_eq!(extract_deprecation_info(None), None);
    }

    #[test]
    fn test_extract_deprecation_info_with_note() {
        let deprecation = Deprecation {
            since: Some("1.0.0".to_string()), // Should be skipped
            note: Some("Use new_function instead".to_string()),
        };
        let result = extract_deprecation_info(Some(&deprecation));
        assert_eq!(
            result,
            Some((true, Some("Use new_function instead".to_string())))
        );
    }

    #[test]
    fn test_extract_deprecation_info_without_note() {
        let deprecation = Deprecation {
            since: Some("1.0.0".to_string()),
            note: None,
        };
        let result = extract_deprecation_info(Some(&deprecation));
        assert_eq!(result, Some((true, None)));
    }

    // =========================================================================
    // Attribute Tests
    // =========================================================================

    #[test]
    fn test_extract_semantic_attrs_must_use() {
        let attrs = vec![Attribute::MustUse { reason: None }];
        let result = extract_semantic_attrs(&attrs);
        assert_eq!(result, vec!["#[must_use]"]);
    }

    #[test]
    fn test_extract_semantic_attrs_must_use_with_reason() {
        let attrs = vec![Attribute::MustUse {
            reason: Some("returns a result that should be checked".to_string()),
        }];
        let result = extract_semantic_attrs(&attrs);
        assert_eq!(
            result,
            vec!["#[must_use(\"returns a result that should be checked\")]"]
        );
    }

    #[test]
    fn test_extract_semantic_attrs_non_exhaustive() {
        let attrs = vec![Attribute::NonExhaustive];
        let result = extract_semantic_attrs(&attrs);
        assert_eq!(result, vec!["#[non_exhaustive]"]);
    }

    #[test]
    fn test_extract_semantic_attrs_multiple() {
        let attrs = vec![
            Attribute::MustUse { reason: None },
            Attribute::NonExhaustive,
        ];
        let result = extract_semantic_attrs(&attrs);
        assert_eq!(result.len(), 2);
        assert!(result.contains(&"#[must_use]".to_string()));
        assert!(result.contains(&"#[non_exhaustive]".to_string()));
    }

    // =========================================================================
    // Function Modifier Tests
    // =========================================================================

    #[test]
    fn test_extract_function_modifiers_default() {
        let header = FunctionHeader {
            is_const: false,
            is_async: false,
            is_unsafe: false,
            abi: Abi::Rust,
        };
        let (is_const, is_async, is_unsafe, abi) = extract_function_modifiers(&header);
        assert!(!is_const);
        assert!(!is_async);
        assert!(!is_unsafe);
        assert_eq!(abi, None);
    }

    #[test]
    fn test_extract_function_modifiers_const() {
        let header = FunctionHeader {
            is_const: true,
            is_async: false,
            is_unsafe: false,
            abi: Abi::Rust,
        };
        let (is_const, _, _, _) = extract_function_modifiers(&header);
        assert!(is_const);
    }

    #[test]
    fn test_extract_function_modifiers_async() {
        let header = FunctionHeader {
            is_const: false,
            is_async: true,
            is_unsafe: false,
            abi: Abi::Rust,
        };
        let (_, is_async, _, _) = extract_function_modifiers(&header);
        assert!(is_async);
    }

    #[test]
    fn test_extract_function_modifiers_unsafe() {
        let header = FunctionHeader {
            is_const: false,
            is_async: false,
            is_unsafe: true,
            abi: Abi::Rust,
        };
        let (_, _, is_unsafe, _) = extract_function_modifiers(&header);
        assert!(is_unsafe);
    }

    #[test]
    fn test_extract_function_modifiers_c_abi() {
        let header = FunctionHeader {
            is_const: false,
            is_async: false,
            is_unsafe: false,
            abi: Abi::C { unwind: false },
        };
        let (_, _, _, abi) = extract_function_modifiers(&header);
        assert_eq!(abi, Some("C".to_string()));
    }

    #[test]
    fn test_extract_function_modifiers_stdcall() {
        let header = FunctionHeader {
            is_const: false,
            is_async: false,
            is_unsafe: false,
            abi: Abi::Stdcall { unwind: false },
        };
        let (_, _, _, abi) = extract_function_modifiers(&header);
        assert_eq!(abi, Some("stdcall".to_string()));
    }

    #[test]
    fn test_extract_function_modifiers_cdecl() {
        let header = FunctionHeader {
            is_const: false,
            is_async: false,
            is_unsafe: false,
            abi: Abi::Cdecl { unwind: false },
        };
        let (_, _, _, abi) = extract_function_modifiers(&header);
        assert_eq!(abi, Some("cdecl".to_string()));
    }

    #[test]
    fn test_extract_function_modifiers_fastcall() {
        let header = FunctionHeader {
            is_const: false,
            is_async: false,
            is_unsafe: false,
            abi: Abi::Fastcall { unwind: false },
        };
        let (_, _, _, abi) = extract_function_modifiers(&header);
        assert_eq!(abi, Some("fastcall".to_string()));
    }

    #[test]
    fn test_extract_function_modifiers_system() {
        let header = FunctionHeader {
            is_const: false,
            is_async: false,
            is_unsafe: false,
            abi: Abi::System { unwind: false },
        };
        let (_, _, _, abi) = extract_function_modifiers(&header);
        assert_eq!(abi, Some("system".to_string()));
    }

    #[test]
    fn test_extract_function_modifiers_other_abi() {
        let header = FunctionHeader {
            is_const: false,
            is_async: false,
            is_unsafe: false,
            abi: Abi::Other("wasm".to_string()),
        };
        let (_, _, _, abi) = extract_function_modifiers(&header);
        assert_eq!(abi, Some("wasm".to_string()));
    }

    #[test]
    fn test_format_function_modifiers_empty() {
        assert_eq!(format_function_modifiers(false, false, false, None), "");
    }

    #[test]
    fn test_format_function_modifiers_const() {
        assert_eq!(
            format_function_modifiers(true, false, false, None),
            "const "
        );
    }

    #[test]
    fn test_format_function_modifiers_async() {
        assert_eq!(
            format_function_modifiers(false, true, false, None),
            "async "
        );
    }

    #[test]
    fn test_format_function_modifiers_unsafe() {
        assert_eq!(
            format_function_modifiers(false, false, true, None),
            "unsafe "
        );
    }

    #[test]
    fn test_format_function_modifiers_extern_c() {
        assert_eq!(
            format_function_modifiers(false, false, false, Some("C")),
            "extern \"C\" "
        );
    }

    #[test]
    fn test_format_function_modifiers_combined() {
        assert_eq!(
            format_function_modifiers(true, true, true, Some("C")),
            "const async unsafe extern \"C\" "
        );
    }

    // =========================================================================
    // Generics Tests
    // =========================================================================

    #[test]
    fn test_format_generics_empty() {
        let generics = Generics {
            params: vec![],
            where_predicates: vec![],
        };
        assert_eq!(format_generics(&generics), None);
    }

    #[test]
    fn test_format_generics_simple_type_param() {
        let generics = Generics {
            params: vec![GenericParamDef {
                name: "T".to_string(),
                kind: GenericParamDefKind::Type {
                    bounds: vec![],
                    default: None,
                    is_synthetic: false,
                },
            }],
            where_predicates: vec![],
        };
        assert_eq!(format_generics(&generics), Some("<T>".to_string()));
    }

    #[test]
    fn test_format_generics_multiple_params() {
        let generics = Generics {
            params: vec![
                GenericParamDef {
                    name: "K".to_string(),
                    kind: GenericParamDefKind::Type {
                        bounds: vec![],
                        default: None,
                        is_synthetic: false,
                    },
                },
                GenericParamDef {
                    name: "V".to_string(),
                    kind: GenericParamDefKind::Type {
                        bounds: vec![],
                        default: None,
                        is_synthetic: false,
                    },
                },
            ],
            where_predicates: vec![],
        };
        assert_eq!(format_generics(&generics), Some("<K, V>".to_string()));
    }

    #[test]
    fn test_format_generics_lifetime_param() {
        let generics = Generics {
            params: vec![GenericParamDef {
                name: "'a".to_string(),
                kind: GenericParamDefKind::Lifetime { outlives: vec![] },
            }],
            where_predicates: vec![],
        };
        assert_eq!(format_generics(&generics), Some("<'a>".to_string()));
    }

    #[test]
    fn test_format_generics_synthetic_filtered() {
        // Synthetic parameters should be filtered out
        let generics = Generics {
            params: vec![GenericParamDef {
                name: "_".to_string(),
                kind: GenericParamDefKind::Type {
                    bounds: vec![],
                    default: None,
                    is_synthetic: true, // This should be filtered
                },
            }],
            where_predicates: vec![],
        };
        assert_eq!(format_generics(&generics), None);
    }

    #[test]
    fn test_format_generics_mixed_synthetic() {
        // Mix of synthetic and non-synthetic
        let generics = Generics {
            params: vec![
                GenericParamDef {
                    name: "_impl".to_string(),
                    kind: GenericParamDefKind::Type {
                        bounds: vec![],
                        default: None,
                        is_synthetic: true,
                    },
                },
                GenericParamDef {
                    name: "T".to_string(),
                    kind: GenericParamDefKind::Type {
                        bounds: vec![],
                        default: None,
                        is_synthetic: false,
                    },
                },
            ],
            where_predicates: vec![],
        };
        assert_eq!(format_generics(&generics), Some("<T>".to_string()));
    }

    #[test]
    fn test_format_generics_const_param() {
        let generics = Generics {
            params: vec![GenericParamDef {
                name: "N".to_string(),
                kind: GenericParamDefKind::Const {
                    type_: rustdoc_types::Type::Primitive("usize".to_string()),
                    default: None,
                },
            }],
            where_predicates: vec![],
        };
        assert_eq!(
            format_generics(&generics),
            Some("<const N: usize>".to_string())
        );
    }

    #[test]
    fn test_format_generics_const_param_with_default() {
        let generics = Generics {
            params: vec![GenericParamDef {
                name: "N".to_string(),
                kind: GenericParamDefKind::Const {
                    type_: rustdoc_types::Type::Primitive("usize".to_string()),
                    default: Some("16".to_string()),
                },
            }],
            where_predicates: vec![],
        };
        assert_eq!(
            format_generics(&generics),
            Some("<const N: usize = 16>".to_string())
        );
    }
}
